export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:bright-black \
  --color=bg:black \
  --color=border:bright-black \
  --color=fg:white \
  --color=gutter:black \
  --color=header:yellow \
  --color=hl+:magenta \
  --color=hl:magenta \
  --color=info:bright-black \
  --color=marker:red \
  --color=pointer:red \
  --color=prompt:blue \
  --color=query:white \
  --color=scrollbar:black \
  --color=separator:yellow \
  --color=spinner:red \
"
