export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:bright-black \
  --color=bg:-1 \
  --color=border:blue \
  --color=fg:-1 \
  --color=gutter:-1 \
  --color=header:yellow \
  --color=hl+:cyan \
  --color=hl:cyan \
  --color=info:bright-black \
  --color=marker:red \
  --color=pointer:red \
  --color=prompt:blue \
  --color=query:7 \
  --color=scrollbar:-1 \
  --color=separator:yellow \
  --color=spinner:red \
"
